### ISSUE TITLE
Updates for sails v0.11

### ISSUE THREAD

**Issue by crobinson42** [balderdashy/backbone-to-sails#12]
Have there been any code updates to this library for sails v0.11?

**Comment by karomancer** [comment]
Bump, would like this to happen soon! Seems like a simple fix too; I think all one has to do is exchange all the references to `socket` in any form (`window.socket`, etc) with `io.socket`.

**Comment by crobinson42** [comment]
I did that but the .fetch() doesn’t seem to be working.

**Comment by karomancer** [comment]
If you're in a bind, I opened a pull request and tweaked it to work with v0.11. 
Note though: I haven't really done any tests other than seeing it work with my own projects, and it looks like the CI test failed; thought it's failing for every PR open
https://github.com/balderdashy/backbone-to-sails/pull/13

It appears not only did we have to change `socket` references to `io.socket` but the `io.socket.request` method changed forms as well:
http://sailsjs.org/#!/documentation/reference/websockets/sails.io.js/socket.request.html

**Comment by designstorming** [comment]
Can you guys test [this fork](https://github.com/designstorming/backbone-to-sails) and give feedback? It's currently in test phase. Thank you in advance.

**Comment by billyshena** [comment]
Any news about an update for sails 0.11v ?

Best,
